### PR TITLE
Ismail

### PR DESCRIPTION
**Pull request by IsmailSharkawy**

### CODE REVIEW

**Comment by IsmailSharkawy** [comment]
only last commit is needed

**Comment by moussa97** [comment]
I can not accept the last commit only , you know that , right ? I can only accept  the merge request as a whole.

**Comment by moussa97** [comment]
Also can you add a description .. what is this merge request for ? @IsmailSharkawy

**Comment by IsmailSharkawy** [comment]
Ignore this pull-request, i made another one just look at that. @moussa97

**Pull request closed without merging**
